export enum DAILY_GOAL_LEVEL {
  BASIC = 'basic',
  CASUAL = 'casual',
  REGULAR = 'regular',
  SERIOUS = 'serious',
  CHALLENGE = 'challenge',
  HARDCORE = 'hardcore',
}

export enum TopicValue {
  POLITICS = "POLITICS",
  WELLNESS = "WELLNESS",
  ENTERTAINMENT = "ENTERTAINMENT",
  PARENTING = "PARENTING",
  STYLE_AND_BEAUTY = "STYLE & BEAUTY",
  GROUPS_VOICES = "GROUPS VOICES",
  TRAVEL = "TRAVEL",
  FOOD_AND_DRINK = "FOOD & DRINK",
  WORLD_NEWS = "WORLD NEWS",
  BUSINESS_AND_FINANCE = "BUSINESS & FINANCES",
  COMEDY = "COMEDY",
  SPORTS = "SPORTS",
  HOME_AND_LIVING = "HOME & LIVING",
  SCIENCE_AND_TECH = "SCIENCE & TECH",
  WEDDINGS = "WEDDINGS",
  ENVIRONMENT = "ENVIRONMENT",
  SETTINGS = "SETTINGS",
  NONE = "NONE",
}